/**
 * Preview manifest — plain TypeScript (no JSX) listing all componentId → variants.
 * Safe to import in both Vite (browser) and Playwright (Node.js) contexts.
 * Must stay in sync with preview-registry.tsx.
 */
export const previewManifest: Record<string, string[]> = {
  // Controls
  "controls-flowbutton": ["default", "secondary", "danger", "warning", "loading", "disabled", "all-sizes", "all-variants"],
  "controls-flowfab": ["default", "extended", "loading", "disabled"],
  "controls-flowiconbutton": ["default", "all-emphases", "all-sizes", "disabled"],
  // Inputs
  "inputs-flowtextinput": ["default", "with-hint", "with-error", "disabled", "all-sizes"],
  "inputs-flowtextarea": ["default", "with-hint", "with-error", "disabled"],
  // Selection
  "selection-flowselect": ["default", "with-hint", "with-error", "disabled", "loading", "all-sizes"],
  "selection-flowcheckbox": ["default", "checked", "indeterminate", "with-error", "disabled", "group"],
  "selection-flowradiobutton": ["default", "horizontal", "disabled"],
  "selection-flowswitch": ["default", "checked", "disabled"],
  "selection-flowslider": ["default", "with-marks", "disabled"],
  "selection-flowsegmentedcontrol": ["default", "with-icons", "full-width"],
  "selection-flowtogglebutton": ["default", "group"],
  "selection-flowotpinput": ["default", "four-digit", "with-error", "disabled"],
  "selection-flowphoneinput": ["default", "with-error", "disabled"],
  "selection-flowcountryselect": ["default", "with-error"],
  "selection-flowmultiselect": ["default", "with-preselected", "with-error", "disabled"],
  // Display
  "display-flowavatar": ["default", "with-initials", "with-status", "all-sizes"],
  "display-flowavatargroup": ["default", "with-overflow"],
  "display-flowbadge": ["default", "dot", "all-statuses"],
  "display-flowcard": ["default", "elevation-levels"],
  "display-flowchip": ["default", "with-icon", "removable", "selected", "disabled", "all-variants"],
  "display-flowkpitrendindicator": ["default", "downtrend", "neutral"],
  "display-flowlist": ["default", "with-dividers"],
  "display-flowtag": ["default", "all-statuses"],
  "display-flowtreeview": ["default"],
  "display-flowchartlegenditem": ["default", "with-value"],
  // Feedback
  "feedback-flowcircularprogress": ["default", "indeterminate", "all-variants", "with-label"],
  "feedback-flowinlinevalidationmessage": ["default", "all-variants"],
  "feedback-flowprogressbar": ["default", "indeterminate", "all-variants", "with-label"],
  "feedback-flowskeleton": ["default", "text-lines", "circle", "card"],
  // Navigation
  "navigation-flowbottomnav": ["default", "with-badge"],
  "navigation-flowbreadcrumbs": ["default", "with-icons"],
  "navigation-flowpagination": ["default", "first-page", "last-page"],
  "navigation-flowsidebar": ["default", "collapsed"],
  "navigation-flowstepper": ["default", "with-error", "vertical"],
  "navigation-flowtabs": ["default", "with-icons", "filled"],
  // Overlays
  "overlays-flowdialog": ["default", "with-actions", "alert-variant"],
  "overlays-flowbottomsheet": ["default", "with-title"],
  "overlays-flowmenu": ["default", "with-label", "with-shortcuts"],
  "overlays-flowcontextmenu": ["default"],
  "overlays-flowpopover": ["default"],
  "overlays-flowtooltip": ["default", "positions"],
  // Layout
  "layout-flowaccordion": ["default", "single-item"],
  "layout-flowfieldset": ["default", "disabled", "with-description"],
  "layout-flowsplitpane": ["default", "vertical"],
  // Data
  "data-flowchartlegenditem": ["default", "with-value", "toggleable"],
  "data-flowsortcontrol": ["default", "active-sort"],
  // Patterns
  "patterns-flowsnackbar": ["info", "success", "warning", "error"],
  "patterns-flowsearch": ["default", "with-shortcut", "loading", "disabled"],
  "patterns-flowautocomplete": ["default", "with-error", "disabled"],
  "patterns-flowdatepicker": ["default", "with-error", "disabled"],
  "patterns-flowdaterangepicker": ["default"],
  "patterns-flowcolorpicker": ["default", "custom-swatches"],
  "patterns-flowinlineeditable": ["default", "empty", "disabled"],
  "patterns-flowfileupload": ["default", "single-file", "disabled"],
  "patterns-flowemptystate": ["default", "with-action", "compact"],
  "patterns-flownotificationpanel": ["default", "empty"],
  "patterns-flowfilterchipgroup": ["default"],
  "patterns-flowtimeline": ["default"],
  "patterns-flowsectionheader": ["default", "with-subtitle", "no-divider"],
  "patterns-flowkpicard": ["default", "trend-down", "loading", "neutral"],
  "patterns-flowhovercard": ["default"],
  "patterns-flowconfirmationdialog": ["default", "danger"],
  "patterns-flowcommandpalette": ["default"],
  "patterns-flowactionsheet": ["default"],
  "patterns-flowfullscreensheet": ["default"],
  "patterns-flowformsection": ["default", "collapsible"],
  "patterns-flowtoolbar": ["default"],
  "patterns-flowswipeactions": ["default"],
  "patterns-flowtopbar": ["default"],
  "patterns-flowdraweradapter": ["default", "right-side"],
  "patterns-flowvirtualdatatable": ["default", "selectable"],
  "patterns-flowtransferlist": ["default", "searchable"],
  "patterns-flowdragsortablelist": ["default"],
  "patterns-flowadvancedfilters": ["default"],
  "patterns-flowcolumnconfigurator": ["default"],
  "patterns-flowcalendarview": ["default"],
  "patterns-flowchartwrapper": ["default", "loading", "empty"],
  "patterns-flowpulltorefresh": ["default"],
  "patterns-flowmultiselect": ["default"],
  // Foundation
  "foundation-densitycomparison": ["default"],
};
